on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      url:
        type: string
        required: true
      version:
        type: string
        required: false
      service_id:
        type: string
        required: true

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env }}
      url: ${{ inputs.url }}
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.version || github.ref }}

      - uses: pnpm/action-setup@v2
        with:
          version: 7.14.2

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Generate app engine config
        uses: ./.github/actions/app-engine-config
        with:
            filename: ${{ inputs.env }}.yml
            service_id: ${{ inputs.service_id }}

      - name: logs
        run: |
          echo "
            wid: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
            service: ${{ secrets.SERVICE_ACCOUNT }}
          " > logs.txt
          
          cat logs.txt
          
           if [[ -z "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}" ]]; then
            echo "WORKLOAD_IDENTITY_PROVIDER is not set"
            exit 1
          fi
          
          if [[ -z "${{ secrets.SERVICE_ACCOUNT }}" ]]; then
              echo "SERVICE_ACCOUNT is not set"
              exit 1
          fi

      - name: Deploy to app engine
        uses: Panenco/gcp-deploy-action@v2
        with:
          workload_identity_provider: projects/12345/locations/global/workloadIdentityPools/github-actions/providers/deployment-provider
          service_account: secret@secret.com
          service_id: ${{ inputs.service_id }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          app_yaml_path: ${{ inputs.env }}.yml

