name: staging-deployment

concurrency:
    group: deploy-staging
    cancel-in-progress: true

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    deploy_staging:
        uses: ./.github/workflows/job_deploy.yml
        with:
          env: staging
          url: https://staging.myapp.dev
          service_id: staging
        secrets:
          WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
