name: temp-env-deployment

concurrency:
  group: temp-env-deployment-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - major/*
      - hotfix/*

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Create a feature name
        id: feature
        uses: Panenco/git-flow/feature@master
        with:
          delimiter: '-'

      - name: Generate app engine config
        uses: ./.github/actions/app-engine-config
        with:
            filename: ${{ steps.feature.outputs.feature_name }}.yml
            service_id: ${{ steps.feature.outputs.feature_name }}

      - name: Deploy to app engine
        uses: Panenco/gcp-deploy-action@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          service_id: ${{ steps.feature.outputs.feature_name }}
          project_id: ${{ vars.GCP_PROJECT_ID }}
          app_yaml_path: ${{ steps.feature.outputs.feature_name }}.yml

      # get the service name and url for better workflow summary
      - name: Set metadata
        id: service_metadata
        run: |
          url=$(gcloud app browse --service=${{ steps.feature.outputs.feature_name }} --no-launch-browser)
          echo "service_name=${{ steps.feature.outputs.feature_name }}" >> $GITHUB_OUTPUT
          echo "service_url=$url" >> $GITHUB_OUTPUT

      - name: Generate Summary
        run: |
          echo "
            ## Summary

            Service name: ${{ steps.service_metadata.outputs.service_name }}
            Service url: ${{ steps.service_metadata.outputs.service_url }}
          " > $GITHUB_STEP_SUMMARY
